Logging:
    FilePath: "dash.log"
    Debug:
        OutputVerbosity: all
        LoggingVerbosity: all
    Release:
        OutputVerbosity: warning
        LoggingVerbosity: warning
Display:
    Fullscreen: false
    Height: 720
    Width: 1280
Graphics:
    BackfaceCulling: false
    VSync: false
UserInterface:
    FilePath: "uitest.html"
    Scale: [ 1.0, 1.0 ]
Editor:
    Port: 8008
