Logging:
    FilePath: "dash.log"
    Debug:
        OutputVerbosity: Debug
        LoggingVerbosity: Debug
    Release:
        OutputVerbosity: Medium
        LoggingVerbosity: Medium
Display:
    Fullscreen: false
    Height: 720
    Width: 1280
Graphics:
    BackfaceCulling: true
    VSync: false
UserInterface:
    FilePath: "uitest.html"
    Scale: [ 1.0, 1.0 ]
Editor:
    Port: 8008
