Logging:
    FilePath: "dash.log"
    Debug:
        OutputVerbosity: !Verbosity Debug
        LoggingVerbosity: !Verbosity Debug
    Release:
        OutputVerbosity: !Verbosity Medium
        LoggingVerbosity: !Verbosity Medium
Display:
    Fullscreen: false
    Height: 900
    Width: 1600
Graphics:
    BackfaceCulling: true
    VSync: false
Physics:
    Gravity: !Vector3 0.0 -10.0 0.0
UserInterface:
    FilePath: "uitest.html"
    Scale: !Vector2 1.0 1.0
