Forward:
  Keyboard:
    - W
Backward:
  Keyboard:
    - S
Jump:
  Keyboard:
    - Space
Quit:
  Keyboard:
    - Escape
Refresh:
  Keyboard:
    - F5
Reset:
  Keyboard:
    - F6
Select:
  Mouse:
    - Left
Spawn:
  Mouse:
    - Right
SendToEditor:
  Keyboard:
    - B
ClubHorn:
  Keyboard:
    - P
TestScroll:
  MouseAxes:
    - ScrollWheel
