Forward:
  Keyboard:
    - W
Backward:
  Keyboard:
    - S
Jump:
  Keyboard:
    - Space
Quit:
  Keyboard:
    - Escape
Refresh:
  Keyboard:
    - F5
Reset:
  Keyboard:
    - F6
Select:
  Mouse:
    - Left
Spawn:
  Mouse:
    - Right
SendToEditor:
  Keyboard:
    - B
ClubHorn:
  Keyboard:
    - A
TestScroll:
  MouseAxes:
    - ScrollWheel
Pause:
  Keyboard:
    - P
Stop:
  Keyboard:
    - O
AnimOne:
  Keyboard:
    - "Keyboard1"
AnimTwo:
  Keyboard:
    - "Keyboard2"
AnimTwoOnce:
  Keyboard:
    - "Keyboard3"
